# Generated by Django 5.2.8 on 2025-11-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.TextField(blank=True, null=True)),
                ('descricao_do_evento', models.TextField(blank=True, null=True)),
                ('foto_do_evento', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vagas_restantes', models.IntegerField(blank=True, null=True)),
                ('participantes_confirmados', models.IntegerField(blank=True, null=True)),
                ('link_pagamento', models.TextField(blank=True, null=True)),
                ('data_e_hora', models.DateTimeField(blank=True, null=True)),
                ('localizacao_cidade', models.TextField(blank=True, null=True)),
                ('localizacao_bairro_endereco', models.TextField(blank=True, null=True)),
                ('categoria_de_esporte', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testemunho', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
