# Generated by Django 5.2.8 on 2025-11-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto_do_evento',
            field=models.ImageField(blank=True, null=True, upload_to='event_pics/'),
        ),
    ]
