# Generated by Django 5.2.8 on 2025-11-10 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_evento_id_criador_alter_inscricao_id_aluno'),
        ('users', '0007_remove_usuario_link_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='id_aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='users.aluno'),
        ),
    ]
