# Generated by Django 5.2.8 on 2025-11-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_inscricao_id_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaevento',
            name='icone',
            field=models.CharField(blank=True, help_text='Cole o emoji aqui (ex: 🏃)', max_length=10, null=True),
        ),
    ]
