# Generated by Django X.X on 2025-11-11 17:05
# (Este arquivo foi gerado, mas o conteúdo abaixo foi preenchido manualmente)

from django.db import migrations

# Lista de categorias para criar, baseada na sua imagem
CATEGORIAS_INICIAIS = [
    {'nome': 'Bike', 'icone': '🚲'},
    {'nome': 'Basquete', 'icone': '🏀'},
    {'nome': 'CrossFit', 'icone': '🏋️'},
    {'nome': 'Yoga', 'icone': '🧘'},
    {'nome': 'Funcional', 'icone': '👟'},
    {'nome': 'Natação', 'icone': '🏊'},
    {'nome': 'Futvôlei', 'icone': '⚽'},
    {'nome': 'Beach Tênis', 'icone': '🎾'},
    {'nome': 'Futebol', 'icone': '⚽'},
    {'nome': 'Vôlei', 'icone': '🏐'},
    {'nome': 'Corrida', 'icone': '🏃'},
]


def popular_categorias(apps, schema_editor):
    """
    Popula o banco com as categorias de evento iniciais.
    Usa o 'nome' como chave de busca.
    """
    # IMPORTANTE: Substitua 'events' pelo nome real do seu app
    # onde o modelo 'Categoria' está definido.
    try:
        Categoria = apps.get_model('events', 'categoriaevento')
    except LookupError:
        print("\n[Erro na Migração]")
        print("Não foi possível encontrar o modelo 'Categoria' no app 'events'.")
        print(
            "Por favor, ajuste o 'get_model('nome_do_app', 'Categoria')' no arquivo de migração.")
        raise

    print("\nPopulando categorias iniciais (usando 'nome' como chave)...")

    for cat_data in CATEGORIAS_INICIAIS:
        # Usando 'nome' como chave principal para get_or_create
        obj, created = Categoria.objects.get_or_create(
            nome=cat_data['nome'],
            defaults={
                'icone': cat_data['icone']
            }
        )
        if created:
            print(f"  -> Criada categoria: {obj.nome}")
        else:
            print(f"  -> Categoria já existe: {obj.nome}")


def remover_categorias(apps, schema_editor):
    """
    Remove as categorias de evento criadas. (Função reversa)
    """
    Categoria = apps.get_model('events', 'Categoria')

    # Pega todos os nomes da nossa lista
    nomes_para_remover = [cat['nome'] for cat in CATEGORIAS_INICIAIS]

    # Deleta todos de uma vez
    print(f"\nRemovendo {len(nomes_para_remover)} categorias...")
    Categoria.objects.filter(nome__in=nomes_para_remover).delete()


class Migration(migrations.Migration):
    dependencies = [
        # IMPORTANTE: Altere isso para apontar para a ÚLTIMA migração
        # do seu app 'events' (ou o app onde 'Categoria' vive).
        # Exemplo: ('events', '0002_alter_evento_campo_x'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(popular_categorias, remover_categorias),
    ]
