# Generated by Django 5.2.8 on 2025-11-11 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_categoriaevento_icone'),
        ('events', '0008_popular_categorias_vibes'),
    ]

    operations = [
    ]
