# Generated by Django 5.2.8 on 2025-11-12 19:25

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_merge_20251111_1408'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='event_gallery/')),
                ('legenda', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='events.evento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_enviadas_evento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de Evento',
                'verbose_name_plural': 'Fotos de Eventos',
                'ordering': ['-created_at'],
            },
            bases=(apps.users.models.ImageResizingMixin, models.Model),
        ),
    ]
