# Generated by Django 5.2.8 on 2025-11-13 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_fotoevento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteracaoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_retorno', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito')], default='pendente', max_length=10)),
                ('lida_pelo_alvo', models.BooleanField(default=False, help_text='Notificação lida pelo dono da inscrição (quem recebeu o 1º like)')),
                ('lida_pelo_autor', models.BooleanField(default=False, help_text="Notificação lida pelo autor (quem recebeu o 'like de volta')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_dadas', to=settings.AUTH_USER_MODEL)),
                ('inscricao_alvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas_recebidas', to='events.inscricao')),
            ],
            options={
                'verbose_name': 'Interação de Presença',
                'verbose_name_plural': 'Interações de Presença',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('autor', 'inscricao_alvo'), name='unique_curtida_presenca')],
            },
        ),
    ]
