# Generated by Django 5.2.8 on 2025-11-13 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_interacaopresenca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='eh_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='aprovado', help_text="Ex: 'pendente', 'aprovado', 'recusado'", max_length=20)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_transacao_externa', models.CharField(blank=True, default='mock_payment', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_recebidos', to='events.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_feitos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'evento'), name='unique_pagamento_usuario_evento')],
            },
        ),
    ]
