# Generated by Django 5.2.8 on 2025-11-10 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_evento_id_criador_alter_inscricao_id_aluno'),
        ('users', '0002_alter_usuario_managers_alter_usuario_url_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Status Social',
                'verbose_name_plural': 'Status Sociais',
            },
        ),
        migrations.CreateModel(
            name='TipoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Conta',
                'verbose_name_plural': 'Tipos de Conta',
            },
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='afinidades',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='horarios_preferidos',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='objetivos',
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='periodos_preferidos',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=20, null=True, verbose_name='Períodos Preferidos'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='preferencias_esporte',
            field=models.ManyToManyField(blank=True, to='events.categoriaevento', verbose_name='Preferências de Esporte'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nivel_pratica',
            field=models.CharField(blank=True, choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], max_length=20, null=True, verbose_name='Nível de Prática'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='vibe_after',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('as_vezes', 'Às vezes')], max_length=10, null=True, verbose_name='Vibe After'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='status_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.statussocial', verbose_name='Status Social'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipo_conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tipoconta', verbose_name='Tipo de Conta'),
        ),
    ]
