# Generated by Django 5.2.8 on 2025-11-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_statussocial_tipoconta_remove_aluno_afinidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('nao_informar', 'Prefiro não responder')], max_length=20, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='num_conselho_classe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
