# Generated by Django 5.2.8 on 2025-11-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_aluno_sexo_profissional_num_conselho_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibeAfterOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Opção de Vibe After',
                'verbose_name_plural': 'Opções de Vibe After',
            },
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='vibe_after',
        ),
        migrations.AddField(
            model_name='aluno',
            name='vibe_after',
            field=models.ManyToManyField(blank=True, to='users.vibeafteropcao', verbose_name='Como é o seu pós-treino?'),
        ),
    ]
