# Generated by Django 5.2.8 on 2025-11-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_vibeafteropcao_remove_aluno_vibe_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
