# Generated by Django 5.2.8 on 2025-11-12 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_fotousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotousuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
