# Generated by Django 5.2.8 on 2025-11-13 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoConexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Conexão',
                'verbose_name_plural': 'Solicitações de Conexão',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('solicitante', 'solicitado'), name='unique_solicitacao_conexao')],
            },
        ),
    ]
