# Generated by Django 5.2.8 on 2025-11-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_solicitacaoconexao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoconexao',
            name='lida_pelo_solicitante',
            field=models.BooleanField(default=False, help_text="Indica se o solicitante já viu a notificação de 'aceita'."),
        ),
    ]
