# Generated by Django 5.2.8 on 2025-11-14 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_popular_planos_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Aluno Premium Mensal, Profissional Pro Anual', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Identificador único para uso no código (ex: aluno-premium-mensal)', max_length=100, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('aluno', 'Aluno Premium'), ('profissional', 'Profissional Pro')], help_text='Para qual tipo de usuário este plano se aplica', max_length=20)),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], help_text='Com que frequência o plano é cobrado', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor cobrado por período', max_digits=10)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, help_text='Desconto aplicado (ex: planos anuais com 20% de desconto)', max_digits=5)),
                ('ativo', models.BooleanField(default=True, help_text='Se False, este plano não aparecerá nas opções de compra')),
                ('destaque', models.BooleanField(default=False, help_text="Se True, este plano será destacado como 'Mais Popular' ou 'Recomendado'")),
                ('descricao', models.TextField(blank=True, help_text='Descrição curta do plano')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor número aparece primeiro)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Plano',
                'verbose_name_plural': 'Tipos de Planos',
                'ordering': ['tipo_usuario', 'ordem', 'periodicidade'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaPremium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('pendente', 'Pendente Pagamento')], default='pendente', max_length=20)),
                ('data_inicio', models.DateTimeField(help_text='Quando a assinatura começou ou começará')),
                ('data_expiracao', models.DateTimeField(help_text='Quando a assinatura expira')),
                ('data_cancelamento', models.DateTimeField(blank=True, help_text='Quando o usuário solicitou o cancelamento', null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, help_text='Valor efetivamente pago por este período', max_digits=10)),
                ('id_transacao_externa', models.CharField(blank=True, help_text='ID da transação no gateway de pagamento', max_length=100)),
                ('metodo_pagamento', models.CharField(blank=True, help_text='Ex: cartao_credito, pix, boleto', max_length=50)),
                ('renovacao_automatica', models.BooleanField(default=False, help_text='Se True, tentará renovar automaticamente ao expirar')),
                ('cancelada_pelo_usuario', models.BooleanField(default=False, help_text='Se True, o usuário não quer renovar')),
                ('observacoes', models.TextField(blank=True, help_text='Notas internas sobre esta assinatura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas_premium', to=settings.AUTH_USER_MODEL)),
                ('tipo_plano', models.ForeignKey(help_text='Qual plano foi contratado', on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='users.tipoplano')),
            ],
            options={
                'verbose_name': 'Assinatura Premium',
                'verbose_name_plural': 'Assinaturas Premium',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'status'], name='users_assin_usuario_bdedc8_idx'), models.Index(fields=['data_expiracao', 'status'], name='users_assin_data_ex_86ed44_idx')],
            },
        ),
    ]
