# Generated by Django 5.2.8 on 2025-11-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_popular_planos_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='metodo_registro',
            field=models.CharField(choices=[('email', 'Email/Senha'), ('google', 'Google OAuth2')], default='email', help_text='Método usado no primeiro cadastro', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil_escolhido',
            field=models.BooleanField(default=False, help_text='Indica se o usuário já escolheu ser Aluno ou Profissional'),
        ),
    ]
